org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.caching=true

mod_id=oneslib
mod_name=Ones Lib
mod_license=All Rights Reserved
mod_version=1.0.1
mod_group_id=com.binaris.oneslib
mod_authors=Binaris
mod_description=Library for registering playable morphs (Ones) with keybind abilities on Forge 1.20.1.

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

geckolib_version=4.4.4
walkers_version=4.4.3
remorphed_version=3.6.2
craftedcore_version=4.2.3
